#include <setjmp.h>

extern "C" __attribute__((naked)) int setjmp(jmp_buf env) {
    asm volatile(
        ".intel_syntax noprefix\n"
        "mov [rdi + 0], rbx\n"
        "lea rax, [rsp + 8]\n"
        "mov [rdi + 8], rax\n"
        "mov [rdi + 16], rbp\n"
        "mov [rdi + 24], rsi\n"
        "mov [rdi + 32], rdi\n"
        "mov [rdi + 40], r12\n"
        "mov [rdi + 48], r13\n"
        "mov [rdi + 56], r14\n"
        "mov [rdi + 64], r15\n"
        "mov rax, [rsp]\n"
        "mov [rdi + 72], rax\n"
        "stmxcsr [rdi + 80]\n"
        "fnstcw [rdi + 84]\n"
        "movdqu xmmword ptr [rdi + 96], xmm6\n"
        "movdqu xmmword ptr [rdi + 112], xmm7\n"
        "movdqu xmmword ptr [rdi + 128], xmm8\n"
        "movdqu xmmword ptr [rdi + 144], xmm9\n"
        "movdqu xmmword ptr [rdi + 160], xmm10\n"
        "movdqu xmmword ptr [rdi + 176], xmm11\n"
        "movdqu xmmword ptr [rdi + 192], xmm12\n"
        "movdqu xmmword ptr [rdi + 208], xmm13\n"
        "movdqu xmmword ptr [rdi + 224], xmm14\n"
        "movdqu xmmword ptr [rdi + 240], xmm15\n"
        "xor eax, eax\n"
        "ret\n"
        ".att_syntax prefix\n");
}

extern "C" __attribute__((naked, noreturn)) void longjmp(jmp_buf env, int value) {
    asm volatile(
        ".intel_syntax noprefix\n"
        "mov rcx, rdi\n"
        "mov r8d, esi\n"
        "test r8d, r8d\n"
        "jne 1f\n"
        "mov r8d, 1\n"
        "1:\n"
        "ldmxcsr [rcx + 80]\n"
        "fldcw [rcx + 84]\n"
        "movdqu xmm6, xmmword ptr [rcx + 96]\n"
        "movdqu xmm7, xmmword ptr [rcx + 112]\n"
        "movdqu xmm8, xmmword ptr [rcx + 128]\n"
        "movdqu xmm9, xmmword ptr [rcx + 144]\n"
        "movdqu xmm10, xmmword ptr [rcx + 160]\n"
        "movdqu xmm11, xmmword ptr [rcx + 176]\n"
        "movdqu xmm12, xmmword ptr [rcx + 192]\n"
        "movdqu xmm13, xmmword ptr [rcx + 208]\n"
        "movdqu xmm14, xmmword ptr [rcx + 224]\n"
        "movdqu xmm15, xmmword ptr [rcx + 240]\n"
        "mov r11, [rcx + 72]\n"
        "mov rbx, [rcx + 0]\n"
        "mov rsp, [rcx + 8]\n"
        "mov rbp, [rcx + 16]\n"
        "mov rsi, [rcx + 24]\n"
        "mov rdi, [rcx + 32]\n"
        "mov r12, [rcx + 40]\n"
        "mov r13, [rcx + 48]\n"
        "mov r14, [rcx + 56]\n"
        "mov r15, [rcx + 64]\n"
        "mov eax, r8d\n"
        "jmp r11\n"
        ".att_syntax prefix\n");
}
